[macos]
installs-with = ["quickset-org/recipes:homebrew"]
command = "starship"

[linux]
installs-with = ["quickset-org/recipes:homebrew"]
command = "starship"
post-install = """
echo 'eval "$(starship init zsh)"' >> ~/.zshrc;
echo 'eval "$(starship init zsh)"' >> ~/.bashrc;
"""
not-finished = true
notes = "Need to make sure the above append to *rc files works"

[windows10]
installs-with = ["quickset-org/recipes:scoop"]
command = "starship"
post-install = "New-item -type file -force $profile; Find profile and add starship init to it"
not-finished = true