[macos]
installs-with = "quickset-org/recipes:homebrew"
command = "jabba"

[linux]
installs-with = "quickset-org/recipes:homebrew"
command = "jabba"

[windows10]
installs-with = "quickset-org/recipes:scoop"
command = "jabba"
